version: '3'
volumes:
    dados:
services:
    db:
        image: postgres:9.6.0
        volumes:
            - dados:/var/lib/postgresql/data
            - ./scripts:/scripts/
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    frontend:
        image: nginx:1.13
        volumes:
            # Site
            - ./web:/usr/share/nginx/html
            #Configuração do proxy reverso
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 9000:80
    app:
        image: python:3.6
        volumes:
            # Aplicação
            - ./app:/app
        working_dir: /app
        command: bash ./app.sh
        # Como está sendo usado proxy reverso, não há necessidade de se acessar a porta diretamente.        
        # ports:
           # - 8080:8080

